### ISSUE TITLE
Updated pkdb_analysis breaks midazolam analysis scripts

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb_analysis#40]
@janekg89 We have to update the code here, so that the analysis work.
It is about reading PK parameters for a subset of studies. This worked in the old version, but due to breaking changes is not working at the moment.

- `query.py`
- `pkdb_stats.py`
- `create_tables.py`
- `experiments/misc/pkscandata.py`

**Comment by janekg89** [comment]
Working scripts: 
- `query.py`
- `pkdb_stats.py`
- `create_tables.py`

how to test `experiments/misc/pkscandata.py`? Running simulations scan simulations fail. If this is still due to new format of pkdata I need help with debugging.
